### ISSUE TITLE
Equalize HttpOptions of ODataService Request with options of HttpClient

### ISSUE THREAD

**Issue by chumbalum** [riccardomariani/odata-v4-ng#2]
Hi,

I'm using the Library for a new project and it's working fine so far (even though I'm working with a v2 Backend). One minor flaw which would be nice to be addressed is the HttpOptions behaviour of ODataService.

In the ordinary HttpClient, it is possible to pass an object with partial properties to be set for requests. As far as I know, this is not possible with the ODataService Requests. An Request with ODataService expects an Object of Type HttpOptions which cannot be instantiated with a "partial" object.

It would be nice to have that feature, because there are situations where you, for example, just need to set a single header. With the current behaviour, a full object needs to be passed.

Below is an example of the "problem". First with the normal HttpClient, the same with ODataService and finally a working configuration of ODataService.

![grafik](https://user-images.githubusercontent.com/486034/39243301-4851f272-488d-11e8-9f32-5d678db945cb.png)

**Comment by riccardomariani** [comment]
Hi @chumbalum,
Thanks for reporting the issue and for the explanation.
I investigated the problem and I'll fix it asap.
Let me ask a couple of questions though just to clarify myself.
Are you using the ODataService object directly? If yes, do you know that you could run queries using the ODataQuery itself? Anyway this does not solve your problem.
In the fix I would not expose the properties "observe" and "responseType" because their current fixed value is required by the library. Is it a problem for you?

**Comment by chumbalum** [comment]
Hi @riccardomariani 

no I'm not using the ODataService directly. I'm using the query object as shown in the code examples. The above code was just for simple documentation.

Concerning observe and responseType, I don't need to specify those properties. So from my point of view, that would do the job.

Thanks for your reply.

**Comment by riccardomariani** [comment]
hi @chumbalum,
I'm implementing the changes to fix this problem and the changes are backward compatible.
I only have the following "collateral" problem. 
According to the Angular specification headers are defined as
`    headers?: HttpHeaders | {
        [header: string]: string | string[];
    };`
Do you know a way to get/set a value from/to headers without taking into account the type of headers?
I mean wherever I need to use headers I don't want to do something like: 
`headers instanceof HttpHeaders ? headers.get('key') : headers['key']`
If there is no way to avoid that I would like to define the headers in the library simply as:
`    headers?: HttpHeaders;`
and the same for params.
Is it a problem for you?

**Comment by riccardomariani** [comment]
Fixed in version 1.0.3, commit 99213060eb8d8feb687aed956ec2f0979cd805b4
