### ISSUE TITLE
HttpHeaders of individual requests present in a BatchRequest are not copied in the body

### ISSUE THREAD

**Issue by chumbalum** [riccardomariani/odata-v4-ng#3]
Hi,

I have another enhancement request for the library :) I have the problem that headers for individual requests in a batch request are not added to the batch body. Specifically I have a backend system which defaults to xml response and therefore I have to set an "Accept: application/json" in each request header, although the header is set in the surrounding batch request. Currently, HttpOptions for requests in a batch are not reflected (apart from IF_MATCH).

I guess the logic has to be implemented in here:

https://github.com/riccardomariani/odata-v4-ng/blob/1da87980c9e8bcfdd04808e3dc08ae45477ce2c4/src/app/odata/odata-query/odata-query-batch.ts#L152

My workaround was to edit the dist files and include a fixed header

![grafik](https://user-images.githubusercontent.com/486034/39427600-aed7eb00-4c84-11e8-81cc-e79eda780d6a.png)

Greetings,
chumbalum

**Comment by riccardomariani** [comment]
Hi @chumbalum,
your analysis is correct. ALL the headers of each individual request contained in a batch request should be copied in the body of the batch request in the part corresponding to the individual request.

Apart from that, I'm wondering if it could make sense and there could be a clean way to provide default headers to apply to all the individual requests and make the headers of each individual request overriding the default ones when provided. 
I mean something like this `new ODataQuery().batch().defaultHeaders(httpHeaders).get(...,httpOptions).post(...,httpOptions)`.
What do you think?

**Comment by chumbalum** [comment]
Hi @riccardomariani 

yes I think that would be a nice convenient feature. If it's too much work, I guess copying headers per request is sufficient for the first enhancement.

greetings,
chumbalum

**Comment by riccardomariani** [comment]
fixed in commit 75b0bfbdbb7a7fb22969d9ae815bf39814c0d6c3
