### ISSUE TITLE
rxjs6 compatibility

### ISSUE THREAD

**Issue by iwantwin** [riccardomariani/odata-v4-ng#5]
Currently odata-v4-ng is not compatible with rxjs version 6.*, which is used by the latest Angular version. This requires users of odata-v4-ng to use the rxjs-compat library. 

Currently this is the only library that requires me to use rxjs in my project.

If you'd like I could create a PR in the beginning of next week upgrading to rxjs v6, let me know!

**Comment by riccardomariani** [comment]
Sorry for being late, I'll update the project in just few days :-)

**Comment by riccardomariani** [comment]
fixed in commit a8bb3fc8875f45ae57f4edfa14f0fd5e6b0b4d3e

**Comment by iwantwin** [comment]
Thanks,  works like a charm!
